// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CurrencyPriceQuoteResponse contains an array of quote response from each quote provider
// swagger:model CurrencyPriceQuoteResponse
type CurrencyPriceQuoteResponse struct {

	// currency price quotes
	CurrencyPriceQuotes []*CurrencyPriceQuote `json:"currency_price_quotes"`
}

// Validate validates this currency price quote response
func (m *CurrencyPriceQuoteResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrencyPriceQuotes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CurrencyPriceQuoteResponse) validateCurrencyPriceQuotes(formats strfmt.Registry) error {

	if swag.IsZero(m.CurrencyPriceQuotes) { // not required
		return nil
	}

	for i := 0; i < len(m.CurrencyPriceQuotes); i++ {

		if swag.IsZero(m.CurrencyPriceQuotes[i]) { // not required
			continue
		}

		if m.CurrencyPriceQuotes[i] != nil {

			if err := m.CurrencyPriceQuotes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("currency_price_quotes" + "." + strconv.Itoa(i))
				}
				return err
			}

		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CurrencyPriceQuoteResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CurrencyPriceQuoteResponse) UnmarshalBinary(b []byte) error {
	var res CurrencyPriceQuoteResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
